import { Category, Product, StoreSetting } from "@/types";

export const DEFAULT_STORE_SETTING: StoreSetting = {
  id: "default-setting",
  storeName: "Kue-KU Artisanal Christmas Bakery",
  phone: "081289001225",
  flatShippingFee: 20000,
  deliveryAreaNotes: "Pengantaran khusus area Jabodetabek & sekitarnya via kurir khusus kue (Radius s/d 25km).",
  announcement: "🎄 Pemesanan Spesial Natal 2026 Dibuka! Slot Pengantaran Terbatas untuk Menjaga Kualitas Segar.",
  isStoreOpen: true,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-kering",
    name: "Kue Kering Toples",
    slug: "kue-kering",
    description: "Kue kering klasik favorit keluarga dengan butter Wisman premium dan keju edam asli.",
    sortOrder: 1,
  },
  {
    id: "cat-cake",
    name: "Cake & Roll Spesial",
    slug: "cake-dan-roll",
    description: "Bolu gulung lembut dan cake perayaan bertema Natal dengan dekorasi meriah.",
    sortOrder: 2,
  },
  {
    id: "cat-hampers",
    name: "Hampers & Gift Box",
    slug: "hampers-natal",
    description: "Paket bingkisan Natal eksklusif dalam kotak kayu & pita beludru, siap kirim ke orang terkasih.",
    sortOrder: 3,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Nastar Wisman Spesial Natal",
    slug: "nastar-wisman-spesial",
    description: "Nastar bertekstur lembut lumer di lidah, dibuat dari 100% mentega Wisman berkualitas tinggi dengan isian selai nanas madu segar racikan rumahan yang legit dan asam manis seimbang.",
    image: "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-kering",
    isAvailable: true,
    isFeatured: true,
    badge: "⭐ Best Seller",
    allergenInfo: "Mengandung mentega Wisman, telur, tepung terigu, susu.",
    variants: [
      {
        id: "var-1-1",
        productId: "prod-1",
        name: "Toples Segi 350g",
        weightGram: 350,
        price: 115000,
        stock: 45,
        isAvailable: true,
      },
      {
        id: "var-1-2",
        productId: "prod-1",
        name: "Toples Bulat Besar 500g",
        weightGram: 500,
        price: 155000,
        stock: 35,
        isAvailable: true,
      },
      {
        id: "var-1-3",
        productId: "prod-1",
        name: "Double Jar Gift Sleeve",
        weightGram: 700,
        price: 235000,
        stock: 20,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-2",
    name: "Kastengel Keju Edam Tua & Gouda",
    slug: "kastengel-keju-edam",
    description: "Kue kering keju asin gurih renyah dengan paduan keju Edam tua impor Belanda dan taburan parutan keju Gouda panggang keemasan yang berlimpah.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-kering",
    isAvailable: true,
    isFeatured: true,
    badge: "🧀 Favorit Keju",
    allergenInfo: "Mengandung keju Edam & Gouda, mentega butter, telur, gluten.",
    variants: [
      {
        id: "var-2-1",
        productId: "prod-2",
        name: "Toples Segi 350g",
        weightGram: 350,
        price: 125000,
        stock: 40,
        isAvailable: true,
      },
      {
        id: "var-2-2",
        productId: "prod-2",
        name: "Toples Bulat Besar 500g",
        weightGram: 500,
        price: 170000,
        stock: 30,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-3",
    name: "Putri Salju Mede Vanilla",
    slug: "putri-salju-mede",
    description: "Kue putri salju berbentuk bulan sabit dengan cincangan kacang mede panggang renyah, dibalut taburan gula salju dingin manis harum aroma vanili Madagascar.",
    image: "https://images.unsplash.com/photo-1548848221-0c2e497ed557?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-kering",
    isAvailable: true,
    isFeatured: false,
    badge: "❄️ Edisi Salju",
    allergenInfo: "Mengandung kacang mede, mentega, telur, susu.",
    variants: [
      {
        id: "var-3-1",
        productId: "prod-3",
        name: "Toples Segi 350g",
        weightGram: 350,
        price: 105000,
        stock: 50,
        isAvailable: true,
      },
      {
        id: "var-3-2",
        productId: "prod-3",
        name: "Toples Bulat Besar 500g",
        weightGram: 500,
        price: 145000,
        stock: 30,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-4",
    name: "Sagu Keju Cheddar Lembut Lumer",
    slug: "sagu-keju-cheddar",
    description: "Kue sagu keju tradisional bertekstur sangat renyah di awal dan seketika lumer di dalam mulut dengan gurih santan dan keju cheddar panggang.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-kering",
    isAvailable: true,
    isFeatured: false,
    badge: null,
    allergenInfo: "Mengandung keju cheddar, telur, santan kelapa, tapioka.",
    variants: [
      {
        id: "var-4-1",
        productId: "prod-4",
        name: "Toples Segi 350g",
        weightGram: 350,
        price: 95000,
        stock: 35,
        isAvailable: true,
      },
      {
        id: "var-4-2",
        productId: "prod-4",
        name: "Toples Bulat Besar 500g",
        weightGram: 500,
        price: 130000,
        stock: 25,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-5",
    name: "Classic Yule Log Cake Cokelat Belgia",
    slug: "classic-yule-log-cake",
    description: "Bolu gulung batang kayu otentik tradisi Natal Eropa, dibalut lapisan ganache cokelat Belgia gelap 70% dengan tekstur serat kayu dan taburan gula icing mirip salju musim dingin.",
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-cake",
    isAvailable: true,
    isFeatured: true,
    badge: "🎄 Ikon Natal",
    allergenInfo: "Mengandung cokelat murni, susu, mentega, telur, gluten.",
    variants: [
      {
        id: "var-5-1",
        productId: "prod-5",
        name: "Ukuran Sedang (Panjang 20cm)",
        weightGram: 600,
        price: 195000,
        stock: 20,
        isAvailable: true,
      },
      {
        id: "var-5-2",
        productId: "prod-5",
        name: "Ukuran Besar Pesta (Panjang 30cm)",
        weightGram: 950,
        price: 275000,
        stock: 15,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-6",
    name: "Spiku Kuno Lapis Surabaya Natal",
    slug: "spiku-kuno-lapis-surabaya",
    description: "Kue lapis Surabaya kuno 3 layer dengan resep warisan 30 kuning telur dan mentega butter wangi, diolesi selai stroberi segar dan dihias cake topper Natal eksklusif.",
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-cake",
    isAvailable: true,
    isFeatured: false,
    badge: "✨ Resep Warisan",
    allergenInfo: "Kuning telur berlimpah, mentega butter, terigu, selai stroberi.",
    variants: [
      {
        id: "var-6-1",
        productId: "prod-6",
        name: "Loyang 20x10 cm",
        weightGram: 500,
        price: 165000,
        stock: 25,
        isAvailable: true,
      },
      {
        id: "var-6-2",
        productId: "prod-6",
        name: "Loyang Penuh 20x20 cm",
        weightGram: 1000,
        price: 295000,
        stock: 18,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-7",
    name: "Hampers Bethlehem Joy (3 Toples)",
    slug: "hampers-bethlehem-joy",
    description: "Bingkisan mewah Natal berisi 1x Nastar Wisman 350g, 1x Kastengel Keju Edam 350g, dan 1x Putri Salju Mede 350g dalam hardbox bernuansa merah marun & emas lengkap dengan kartu ucapan kustom.",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-hampers",
    isAvailable: true,
    isFeatured: true,
    badge: "🎁 Pilihan Hampers",
    allergenInfo: "Mengandung varian lengkap kue kering (susu, telur, keju, mede, gluten).",
    variants: [
      {
        id: "var-7-1",
        productId: "prod-7",
        name: "Paket Box Hardcase + Pita Satin",
        weightGram: 1400,
        price: 385000,
        stock: 30,
        isAvailable: true,
      },
    ],
  },
  {
    id: "prod-8",
    name: "Hampers Noel Deluxe Majesty",
    slug: "hampers-noel-deluxe",
    description: "Paket hantaran Natal terlengkap dalam keranjang anyam kayu rotan eksklusif: 2 Toples Kue Kering Pilihan, 1 Yule Log Cake 20cm, sendok kue emas, lampu fairy lights, dan kartu Natal elegan.",
    image: "https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=800&q=80",
    categoryId: "cat-hampers",
    isAvailable: true,
    isFeatured: true,
    badge: "👑 Edisi Terbatas",
    allergenInfo: "Koleksi lengkap kue kering dan bolu gulung cokelat.",
    variants: [
      {
        id: "var-8-1",
        productId: "prod-8",
        name: "Keranjang Anyam Rotan Premium",
        weightGram: 2200,
        price: 550000,
        stock: 15,
        isAvailable: true,
      },
    ],
  },
];
